### ISSUE TITLE
pack module

### ISSUE THREAD

**Issue by rofl0r** [revivalizer/compilertalk#4]
```
~/compilertalk/lessons/01_addition$ lua5.3 main.lua 
lua5.3: ./util/export.lua:14: module 'pack' not found:
```
i tried installing the "lpack" module from luarocks, but that doesn't seem to be the correct one.
is it a personal module that's missing ?

**Comment by revivalizer** [comment]
No, this was not something I wrote. I got it through my install of luaforwindows: https://github.com/rjpcomputing/luaforwindows

**Comment by revivalizer** [comment]
Based on this SO answer: https://stackoverflow.com/questions/43192285/lua-5-3-unpacking

"In Lua 5.2, unpack was moved to table.unpack."

Do this at the top of your code `unpack = table.unpack or unpack`

Feel free to submit a Pull Request :)
